onCull = true
MaxEntityEntities = 64
qualityModes = "CRITICAL"
RenderWeather = "CLOSE"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 93.274
chatFix = false
onGui = false
GuiRXTX = false
GuiFPS = false
GuiCPU = false
GuiGPU = false
GuiRAM = false
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = false
Particle = false
BlockBreakParticleMode = "LOW"
MaxParticleDistance = 32
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = true
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "NULL"
EntityCullFov = 120
MinDistance = 5
EntityDistance = 32
TickPerformance = false
