
["Blue Archive Craft Config"]
	#控制小空便利店生成
	"Store Generate" = true
	#控制Cost条是否渲染
	"Cost Render" = true
	#总力战开启计时 (添加binah mod生效)
	"Total Strength Battle Tick On" = true
	#总力战计时 (300000毫秒 = 5分钟)
	"Total Strength Battle Timing" = 300000
	#时停是否时停玩家
	"Time Stop Player" = true
	#渲染光圈
	"Render Halo" = true
	#替换鼠标贴图
	"Replace Mouse" = true
	#播放主界面音乐
	"Play Main Music" = false

